 
title:        Importance Driven Coverage
tagline:      Importance-Driven Deep Learning System Testing
baseurl:      ""
paginate:     1
locale:       "en"

gems:
   - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-dinky

