 
title:        DeepFault
tagline:      Fault Localization For Deep Neural Networks 
baseurl:      ""
paginate:     1
locale:       "en"

gems:
   - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-dinky

